bug:
  - ["bug", "Bug"]
documentation:
  - ["documentation", "Documentation"]
firebase:
  - "firebase"
UI:
  - "UI"
UX:
  - "UX"
help wanted:
  - "help"
good first issue:
  - "good first issue"
CI/CD:
  - "CI/CD"
