name: "GreetContributor"
on:
  issue:
    types: [created, edited]

jobs:
  GreetCommitter:
    runs-on: ubuntu-latest
    steps:
      - name: "Greet contributor"
        uses: ibakshay/greet-contributors-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
