name: "GreetContributor"
on:
  issues:
    types: [opened, edited]

jobs:
  GreetCommitter:
    runs-on: ubuntu-latest
    steps:
      - name: "Greet contributor"
        uses: actions/first-interaction@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
