name: first-interaction

on:
  issues:
    types: [opened]
  pull_request:
    branches: [main, master]
    types: [opened]

jobs:
  check_for_first_interaction:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/first-interaction@main
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Hello 👋🏻 @${{ github.actor }}! Thankyou for creating an issue!"
          pr-message: " Thank you @${{ github.actor }}! for creating your first pull request. It will be reviewed soon"
